// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gQ3KXPDkenauFvm5VgNURFtaZbK2G5g',
    appId: '1:732947090927:web:83ff7105f17b986cfeba1a',
    messagingSenderId: '732947090927',
    projectId: 'usrsingin',
    authDomain: 'usrsingin.firebaseapp.com',
    storageBucket: 'usrsingin.appspot.com',
    measurementId: 'G-YDTY53N8G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMd1mVXO_le68UAyaJ8cmYl42hIMrrpEA',
    appId: '1:732947090927:android:c4095b086984aa56feba1a',
    messagingSenderId: '732947090927',
    projectId: 'usrsingin',
    storageBucket: 'usrsingin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBytHPxz7_aK9fPy7lfJkL56sWFJh8JWec',
    appId: '1:732947090927:ios:f0aab21774b9b6ebfeba1a',
    messagingSenderId: '732947090927',
    projectId: 'usrsingin',
    storageBucket: 'usrsingin.appspot.com',
    iosClientId: '732947090927-t6q22rt0tbvejf25rbqm7p3mpkaoii40.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBytHPxz7_aK9fPy7lfJkL56sWFJh8JWec',
    appId: '1:732947090927:ios:f0aab21774b9b6ebfeba1a',
    messagingSenderId: '732947090927',
    projectId: 'usrsingin',
    storageBucket: 'usrsingin.appspot.com',
    iosClientId: '732947090927-t6q22rt0tbvejf25rbqm7p3mpkaoii40.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
